# Generated by Django 3.0.3 on 2020-03-01 20:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('personal_info', models.TextField()),
                ('skills_info', models.TextField()),
                ('wishes_info', models.TextField()),
                ('extra_info', models.TextField()),
                ('personal_info_extended', models.TextField()),
                ('skills_info_extended', models.TextField()),
                ('wishes_info_extended', models.TextField()),
                ('extra_info_extended', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(default='StartUp', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('RR', 'RECRUITER_REJECTED'), ('RA', 'RECRUITER_ACCEPTED'), ('CR', 'CANDIDATE_REJECTED'), ('CA', 'CANDIDATE_ACCEPTED')], max_length=2)),
                ('last_change_date', models.DateTimeField(default=datetime.datetime.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Candidate')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Recruiter')),
            ],
        ),
    ]
